orbs:
  azure-acr: circleci/azure-acr@x.y.z
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - azure-acr/build-and-push-image:
          login-server-name: awesomeexample.azurecr.io
          registry-name: awesomeExample
          repo: https://github.com/Liewyn/gridcomputing
          tag: $CIRCLE_TAG